/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menú;

import javax.swing.ImageIcon;

/**
 *
 * @author PCZ
 */
public class Menú extends javax.swing.JFrame {

    /**
     * Creates new form Menú
     */
    public Menú() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("top-menu.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_file = new javax.swing.JMenu();
        MFile_load = new javax.swing.JMenuItem();
        MFile_save = new javax.swing.JMenuItem();
        MFile_exit = new javax.swing.JMenuItem();
        Menu_edit = new javax.swing.JMenu();
        MEdit_cut = new javax.swing.JMenuItem();
        MEdit_copy = new javax.swing.JMenuItem();
        MEdit_paste = new javax.swing.JMenuItem();
        MEdit_delete = new javax.swing.JMenuItem();
        Menu_help = new javax.swing.JMenu();
        MHelp_helpContents = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 30, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        Menu_file.setText("File");

        MFile_load.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/file (1).png"))); // NOI18N
        MFile_load.setText("Load");
        MFile_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MFile_loadActionPerformed(evt);
            }
        });
        Menu_file.add(MFile_load);

        MFile_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/save--v1 (1).png"))); // NOI18N
        MFile_save.setText("Save");
        Menu_file.add(MFile_save);

        MFile_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/Logout_37127 (1).png"))); // NOI18N
        MFile_exit.setText("Exit");
        MFile_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MFile_exitActionPerformed(evt);
            }
        });
        Menu_file.add(MFile_exit);

        jMenuBar1.add(Menu_file);

        Menu_edit.setText("Edit");

        MEdit_cut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/cut (1).png"))); // NOI18N
        MEdit_cut.setText("Cut");
        Menu_edit.add(MEdit_cut);

        MEdit_copy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/copy (1).png"))); // NOI18N
        MEdit_copy.setText("Copy");
        MEdit_copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEdit_copyActionPerformed(evt);
            }
        });
        Menu_edit.add(MEdit_copy);

        MEdit_paste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/paste (1).png"))); // NOI18N
        MEdit_paste.setText("Paste");
        MEdit_paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEdit_pasteActionPerformed(evt);
            }
        });
        Menu_edit.add(MEdit_paste);

        MEdit_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/delete (1).png"))); // NOI18N
        MEdit_delete.setText("Delete");
        Menu_edit.add(MEdit_delete);

        jMenuBar1.add(Menu_edit);

        Menu_help.setText("Help");
        Menu_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_helpActionPerformed(evt);
            }
        });

        MHelp_helpContents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i/help (1).png"))); // NOI18N
        MHelp_helpContents.setText("Help Contents");
        Menu_help.add(MHelp_helpContents);

        jMenuBar1.add(Menu_help);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MFile_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MFile_loadActionPerformed
        // TODO add your handling code here:
        MFile_load.setIcon(new ImageIcon(getClass().getResource("/i/file.png")));
    }//GEN-LAST:event_MFile_loadActionPerformed

    private void Menu_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_helpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_helpActionPerformed

    private void MFile_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MFile_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MFile_exitActionPerformed

    private void MEdit_copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEdit_copyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MEdit_copyActionPerformed

    private void MEdit_pasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEdit_pasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MEdit_pasteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menú().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MEdit_copy;
    private javax.swing.JMenuItem MEdit_cut;
    private javax.swing.JMenuItem MEdit_delete;
    private javax.swing.JMenuItem MEdit_paste;
    private javax.swing.JMenuItem MFile_exit;
    private javax.swing.JMenuItem MFile_load;
    private javax.swing.JMenuItem MFile_save;
    private javax.swing.JMenuItem MHelp_helpContents;
    private javax.swing.JMenu Menu_edit;
    private javax.swing.JMenu Menu_file;
    private javax.swing.JMenu Menu_help;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void setIconImage(ImageIcon imageIcon) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
